In [1]:
#pip install pypyodbc

In [2]:
import pandas as pd
import pypyodbc as odbc
import pyodbc

#Example1

import pandas as pd
import pyodbc  # Use pyodbc instead of pypyodbc

# Define your connection string
conn_str = (
    r'DRIVER={SQL Server};'
    r'SERVER=DESKTOP-D320OC2\SQLEXPRESS;'
    r'DATABASE=home;'
    r'Trusted_Connection=yes;'
)

# Establish the connection
try:
    conn = pyodbc.connect(conn_str)
except pyodbc.Error as ex:
    print(f"Connection Error: {ex}")
    raise

# Load data from Excel
df1 = pd.read_excel(r"C:\Users\HP\Desktop\Book2.xlsx", sheet_name="house")

# Convert DataFrame to list of tuples
records1 = df1.to_records(index=False).tolist()

# SQL insert statement
sql_insert = '''
    INSERT INTO house (home_id, home_name) 
    VALUES (?, ?)
'''

# SQL select statement to check for existing records
sql_check = '''
    SELECT COUNT(*) FROM house WHERE home_id = ? AND home_name = ?
'''

# Insert records into the database if they do not already exist
try:
    cursor = conn.cursor()
    for record in records1:
        cursor.execute(sql_check, record)
        if cursor.fetchone()[0] == 0:  # Record does not exist
            cursor.execute(sql_insert, record)
    conn.commit()  # Commit the transaction
except Exception as e:
    conn.rollback()  # Rollback the transaction
    print(f"Error: {str(e)}")
finally:
    cursor.close()
    conn.close()
    print('Task is complete.')

#Example2

import pandas as pd
import pyodbc  # Use pyodbc instead of pypyodbc

# Define your connection string
conn_str = (
    r'DRIVER={SQL Server};'
    r'SERVER=DESKTOP-D320OC2\SQLEXPRESS;'
    r'DATABASE=home;'
    r'Trusted_Connection=yes;'
)

# Establish the connection
try:
    conn = pyodbc.connect(conn_str)
except pyodbc.Error as ex:
    print(f"Connection Error: {ex}")
    raise

# Load data from Excel
df1 = pd.read_excel(r"C:\Users\HP\Desktop\Book2.xlsx", sheet_name="name")

# Convert DataFrame to list of tuples
records1 = df1.to_records(index=False).tolist()

# SQL insert statement
sql_insert = '''
    INSERT INTO name (customer_id, customer_name) 
    VALUES (?, ?)
'''

# SQL select statement to check for existing records
sql_check = '''
    SELECT COUNT(*) FROM name WHERE customer_id = ? AND customer_name = ?
'''

# Insert records into the database if they do not already exist
try:
    cursor = conn.cursor()
    for record in records1:
        cursor.execute(sql_check, record)
        if cursor.fetchone()[0] == 0:  # Record does not exist
            cursor.execute(sql_insert, record)
    conn.commit()  # Commit the transaction
except Exception as e:
    conn.rollback()  # Rollback the transaction
    print(f"Error: {str(e)}")
finally:
    cursor.close()
    conn.close()
    print('Task is complete.')

#example 3

import pandas as pd
import pyodbc  # Use pyodbc instead of pypyodbc

# Define your connection string
conn_str = (
    r'DRIVER={SQL Server};'
    r'SERVER=DESKTOP-D320OC2\SQLEXPRESS;'
    r'DATABASE=home;'
    r'Trusted_Connection=yes;'
)

# Establish the connection
try:
    conn = pyodbc.connect(conn_str)
except pyodbc.Error as ex:
    print(f"Connection Error: {ex}")
    raise

# Load data from Excel
df1 = pd.read_excel(r"C:\Users\HP\Desktop\Book2.xlsx", sheet_name="ownhouse")

# Convert DataFrame to list of tuples
records1 = df1.to_records(index=False).tolist()

# SQL insert statement
sql_insert = '''
    INSERT INTO ownhouse (id,customer_id, home_id) 
    VALUES (?, ?,?)
'''

# SQL select statement to check for existing records
sql_check = '''
    SELECT COUNT(*) FROM ownhouse WHERE id=? and customer_id = ? AND home_id = ? 
'''

# Insert records into the database if they do not already exist
try:
    cursor = conn.cursor()
    for record in records1:
        cursor.execute(sql_check, record)
        if cursor.fetchone()[0] == 0:  # Record does not exist
            cursor.execute(sql_insert, record)
    conn.commit()  # Commit the transaction
except Exception as e:
    conn.rollback()  # Rollback the transaction
    print(f"Error: {str(e)}")
finally:
    cursor.close()
    conn.close()
    print('Task is complete.')

In [3]:
import pyodbc

conn_str = (
    r'DRIVER={ODBC Driver 17 for SQL Server};'
    r'SERVER=DESKTOP-D320OC2\SQLEXPRESS;'
    r'DATABASE=savina;'
    r'TRUSTED_CONNECTION=yes;'
)

conn = pyodbc.connect(conn_str)
cursor = conn.cursor()

sql_script = """
-- Drop existing tables if they exist
DROP TABLE IF EXISTS teamleader;
DROP TABLE IF EXISTS el;
DROP TABLE IF EXISTS lob;
DROP TABLE IF EXISTS eg;
DROP TABLE IF EXISTS genesys;
DROP TABLE IF EXISTS et;
DROP TABLE IF EXISTS title;
DROP TABLE IF EXISTS ef;
DROP TABLE IF EXISTS function_;
DROP TABLE IF EXISTS qa;
DROP TABLE IF EXISTS target;
DROP TABLE IF EXISTS resign;
DROP TABLE IF EXISTS employee;

-- Create tables with matching key column lengths
CREATE TABLE employee (
    ei CHAR(15) NOT NULL PRIMARY KEY,
    full_name NCHAR(50),
    batch CHAR(3),
    join_ttu date,
    join_savina date,
    probation_date date,
    gender CHAR(10),
    dob date,
    gcic CHAR(20),
    personal_email CHAR(50),
    ttu_email CHAR(50),
    mobile_number CHAR(50),
    education nCHAR(20),
    major NCHAR(50),
    gcic_code char(13)
);

CREATE TABLE function_ (
    function_id CHAR(4) NOT NULL PRIMARY KEY,
    function_ CHAR(30)
);

CREATE TABLE ef (
    ef_id CHAR(10) NOT NULL PRIMARY KEY,
    ei CHAR(15) NOT NULL,
    function_id CHAR(4) NOT NULL,
    start_date DATE,
    end_date DATE,
    CONSTRAINT FK_ef_employee FOREIGN KEY (ei) REFERENCES employee(ei),
    CONSTRAINT FK_ef_function FOREIGN KEY (function_id) REFERENCES function_(function_id)
);

CREATE TABLE title (
    title_id CHAR(4) NOT NULL PRIMARY KEY,
    title CHAR(30)
);

CREATE TABLE et (
    et_id CHAR(10) NOT NULL PRIMARY KEY,
    ei CHAR(15) NOT NULL,
    title_id CHAR(4) NOT NULL,
    start_date DATE,
    end_date DATE,
    CONSTRAINT FK_et_employee FOREIGN KEY (ei) REFERENCES employee(ei),
    CONSTRAINT FK_et_title FOREIGN KEY (title_id) REFERENCES title(title_id)
);

CREATE TABLE genesys (
    g_id CHAR(5) NOT NULL PRIMARY KEY,
    genesys CHAR(6)
);

CREATE TABLE eg (
    eg_id CHAR(10) NOT NULL PRIMARY KEY,
    ei CHAR(15) NOT NULL,
    g_id CHAR(5) NOT NULL,
    start_date DATE,
    end_date DATE,
    CONSTRAINT FK_eg_employee FOREIGN KEY (ei) REFERENCES employee(ei),
    CONSTRAINT FK_eg_genesys FOREIGN KEY (g_id) REFERENCES genesys(g_id)
);

CREATE TABLE lob (
    lob_id CHAR(5) NOT NULL PRIMARY KEY,
    lob CHAR(30)
);

CREATE TABLE el (
    elob_id CHAR(10) NOT NULL PRIMARY KEY,
    ei CHAR(15) NOT NULL,
    lob_id CHAR(5) NOT NULL,
    start_date DATE,
    end_date DATE,
    CONSTRAINT FK_el_employee FOREIGN KEY (ei) REFERENCES employee(ei),
    CONSTRAINT FK_el_lob FOREIGN KEY (lob_id) REFERENCES lob(lob_id)
);

CREATE TABLE teamleader (
    etl_id CHAR(10) NOT NULL PRIMARY KEY,
    ei CHAR(15) NOT NULL,
    team_leader NCHAR(20),
    start_date DATE,
    end_date DATE,
    CONSTRAINT FK_teamleader_employee FOREIGN KEY (ei) REFERENCES employee(ei)
);

CREATE TABLE qa (
    eqa_id CHAR(10) NOT NULL PRIMARY KEY,
    ei CHAR(15)  NOT NULL,
    PIC NCHAR(20),
    start_date DATE,
    end_date DATE,
    CONSTRAINT FK_qa_employee FOREIGN KEY (ei) REFERENCES employee(ei)
);

CREATE TABLE target (
    target_id CHAR(10) NOT NULL PRIMARY KEY,
    ei CHAR(15)   NOT NULL,
    target NCHAR(20),
    start_date DATE,
    end_date DATE,
    CONSTRAINT FK_target_employee FOREIGN KEY (ei) REFERENCES employee(ei)
);

CREATE TABLE resign (
    r_id CHAR(10) NOT NULL PRIMARY KEY,
    ei CHAR(15)  NOT NULL,
    status NCHAR(20),
    start_date DATE,
    end_date DATE,
    CONSTRAINT FK_resign_employee FOREIGN KEY (ei) REFERENCES employee(ei)
);
"""

cursor.execute(sql_script)
conn.commit()

cursor.close()
conn.close()

print("Tables created successfully.")

Tables created successfully.

In [4]:
#table 1
import pandas as pd
import pyodbc
from datetime import date

conn_str = (
    r'DRIVER={ODBC Driver 17 for SQL Server};'  
    r'SERVER=DESKTOP-D320OC2\SQLEXPRESS;'
    r'DATABASE=savina;'
    r'Trusted_Connection=yes;'
)

try:
    conn = pyodbc.connect(conn_str)
except pyodbc.Error as ex:
    print(f"Connection Error: {ex}")
    raise

df1 = pd.read_excel(r"C:\Users\HP\Desktop\main TA.xlsx", sheet_name="employee")

df1['join_ttu'] = df1['join_ttu'].dt.date
df1['join_savina'] = df1['join_savina'].dt.date
df1['probation_date'] = df1['probation_date'].dt.date
df1['dob'] = df1['dob'].dt.date
df1['gcic_code'] = df1['gcic_code'].astype(str)


records1 = df1.where(pd.notnull(df1), None).to_records(index=False).tolist()

sql_insert = '''
    INSERT INTO employee (ei, full_name, batch, join_ttu, join_savina, probation_date,
    gender, dob, gcic, personal_email, ttu_email, mobile_number, education, major,gcic_code) 
    VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,?)
'''

sql_check = '''
    SELECT COUNT(*) FROM employee WHERE ei = ? 
'''

try:
    cursor = conn.cursor()
    for record in records1:
        cursor.execute(sql_check, record[0])  
        if cursor.fetchone()[0] == 0:  
            cursor.execute(sql_insert, record)
    conn.commit()  
except Exception as e:
    conn.rollback()  
    print(f"Error: {str(e)}")
finally:
    cursor.close()
    conn.close()
    print('Task is complete.')

Task is complete.

In [5]:
#table 2 -- function


conn_str = (
    r'DRIVER={ODBC Driver 17 for SQL Server};'  
    r'SERVER=DESKTOP-D320OC2\SQLEXPRESS;'
    r'DATABASE=savina;'
    r'Trusted_Connection=yes;'
)

try:
    conn = pyodbc.connect(conn_str)
except pyodbc.Error as ex:
    print(f"Connection Error: {ex}")
    raise

df1 = pd.read_excel(r"C:\Users\HP\Desktop\main TA.xlsx", sheet_name="function")
df1 = df1[['function_id', 'function']]


records1 = df1.where(pd.notnull(df1), None).to_records(index=False).tolist()

sql_insert = '''
    INSERT INTO function_ (function_id, function_) 
    VALUES (?, ?)
'''

sql_check = '''
    SELECT COUNT(*) FROM function_ WHERE function_id = ? 
'''

try:
    cursor = conn.cursor()
    for record in records1:
        cursor.execute(sql_check, record[0])  
        if cursor.fetchone()[0] == 0:  
            cursor.execute(sql_insert, record)
    conn.commit()  
except Exception as e:
    conn.rollback()  
    print(f"Error: {str(e)}")
finally:
    cursor.close()
    conn.close()
    print('Task is complete.')

Task is complete.

In [6]:
# table 3


conn_str = (
    r'DRIVER={ODBC Driver 17 for SQL Server};'  
    r'SERVER=DESKTOP-D320OC2\SQLEXPRESS;'
    r'DATABASE=savina;'
    r'Trusted_Connection=yes;'
)

try:
    conn = pyodbc.connect(conn_str)
except pyodbc.Error as ex:
    print(f"Connection Error: {ex}")
    raise

try:
    cursor = conn.cursor()
    cursor.execute('DELETE FROM ef;')
    conn.commit()

    df1 = pd.read_excel(r"C:\Users\HP\Desktop\main TA.xlsx", sheet_name="ef")

    df1['start_date'] = df1['start_date'].dt.date
    df1['end_date'] = df1['end_date'].dt.date

    records1 = df1.where(pd.notnull(df1), None).to_records(index=False).tolist()

    sql_insert = '''
        INSERT INTO ef (ef_id, ei, function_id, start_date, end_date) 
        VALUES (?, ?, ?, ?, ?)
    '''

    for record in records1:
        cursor.execute(sql_insert, record)

    conn.commit()  
except Exception as e:
    conn.rollback()  
    print(f"Error: {str(e)}")
finally:
    cursor.close()
    conn.close()
    print('Task is complete.')

Task is complete.

In [7]:
#table 4--lob

conn_str = (
    r'DRIVER={ODBC Driver 17 for SQL Server};'  
    r'SERVER=DESKTOP-D320OC2\SQLEXPRESS;'
    r'DATABASE=savina;'
    r'Trusted_Connection=yes;'
)

try:
    conn = pyodbc.connect(conn_str)
except pyodbc.Error as ex:
    print(f"Connection Error: {ex}")
    raise

df1 = pd.read_excel(r"C:\Users\HP\Desktop\main TA.xlsx", sheet_name="lob")

df1 = df1[['lob_id', 'lob']]

records1 = df1.where(pd.notnull(df1), None).to_records(index=False).tolist()

sql_insert = '''
    INSERT INTO lob (lob_id, lob) 
    VALUES (?, ?)
'''

sql_check = '''
    SELECT COUNT(*) FROM lob WHERE lob_id = ? 
'''

try:
    cursor = conn.cursor()
    for record in records1:
        cursor.execute(sql_check, record[0])  
        if cursor.fetchone()[0] == 0:  
            cursor.execute(sql_insert, record)
    conn.commit()  
except Exception as e:
    conn.rollback()  
    print(f"Error: {str(e)}")
finally:
    cursor.close()
    conn.close()
    print('Task is complete.')

Task is complete.

In [8]:
#table 5--title


conn_str = (
    r'DRIVER={ODBC Driver 17 for SQL Server};'  
    r'SERVER=DESKTOP-D320OC2\SQLEXPRESS;'
    r'DATABASE=savina;'
    r'Trusted_Connection=yes;'
)

try:
    conn = pyodbc.connect(conn_str)
except pyodbc.Error as ex:
    print(f"Connection Error: {ex}")
    raise

df1 = pd.read_excel(r"C:\Users\HP\Desktop\main TA.xlsx", sheet_name="title")

df1 = df1[['title_id', 'title']]

records1 = df1.where(pd.notnull(df1), None).to_records(index=False).tolist()

sql_insert = '''
    INSERT INTO title (title_id, title) 
    VALUES (?, ?)
'''

sql_check = '''
    SELECT COUNT(*) FROM title WHERE title_id = ? 
'''

try:
    cursor = conn.cursor()
    for record in records1:
        cursor.execute(sql_check, record[0])  
        if cursor.fetchone()[0] == 0:  
            cursor.execute(sql_insert, record)
    conn.commit()  
except Exception as e:
    conn.rollback()  
    print(f"Error: {str(e)}")
finally:
    cursor.close()
    conn.close()
    print('Task is complete.')

Task is complete.

In [9]:
## table 6 gene


conn_str = (
    r'DRIVER={ODBC Driver 17 for SQL Server};'  
    r'SERVER=DESKTOP-D320OC2\SQLEXPRESS;'
    r'DATABASE=savina;'
    r'Trusted_Connection=yes;'
)

try:
    conn = pyodbc.connect(conn_str)
except pyodbc.Error as ex:
    print(f"Connection Error: {ex}")
    raise

df1 = pd.read_excel(r"C:\Users\HP\Desktop\main TA.xlsx", sheet_name="genesys")

df1 = df1[['g_id', 'genesys']]

records1 = df1.where(pd.notnull(df1), None).to_records(index=False).tolist()

sql_insert = '''
    INSERT INTO genesys (g_id, genesys) 
    VALUES (?, ?)
'''

sql_check = '''
    SELECT COUNT(*) FROM genesys WHERE g_id = ? 
'''

try:
    cursor = conn.cursor()
    for record in records1:
        cursor.execute(sql_check, record[0]) 
        if cursor.fetchone()[0] == 0:  
            cursor.execute(sql_insert, record)
    conn.commit()  
except Exception as e:
    conn.rollback()  
    print(f"Error: {str(e)}")
finally:
    cursor.close()
    conn.close()
    print('Task is complete.')

Task is complete.

In [10]:
#table 7


conn_str = (
    r'DRIVER={ODBC Driver 17 for SQL Server};'  
    r'SERVER=DESKTOP-D320OC2\SQLEXPRESS;'
    r'DATABASE=savina;'
    r'Trusted_Connection=yes;'
)

try:
    conn = pyodbc.connect(conn_str)
except pyodbc.Error as ex:
    print(f"Connection Error: {ex}")
    raise

df1 = pd.read_excel(r"C:\Users\HP\Desktop\main TA.xlsx", sheet_name="et")

df1['start_date'] = df1['start_date'].dt.date
df1['end_date'] = df1['end_date'].dt.date

records1 = df1.where(pd.notnull(df1), None).to_records(index=False).tolist()

sql_delete = '''
    DELETE FROM et;
'''

sql_insert = '''
    INSERT INTO et (et_id, ei, title_id, start_date, end_date) 
    VALUES (?, ?, ?, ?, ?)
'''

try:
    cursor = conn.cursor()
    cursor.execute(sql_delete)  
    
    for record in records1:
        cursor.execute(sql_insert, record)
    
    conn.commit() 
except Exception as e:
    conn.rollback()  
    print(f"Error: {str(e)}")
finally:
    cursor.close()
    conn.close()
    print('Task is complete.')

Task is complete.

In [11]:
#table 8 

conn_str = (
    r'DRIVER={ODBC Driver 17 for SQL Server};' 
    r'SERVER=DESKTOP-D320OC2\SQLEXPRESS;'
    r'DATABASE=savina;'
    r'Trusted_Connection=yes;'
)

try:
    conn = pyodbc.connect(conn_str)
except pyodbc.Error as ex:
    print(f"Connection Error: {ex}")
    raise

df1 = pd.read_excel(r"C:\Users\HP\Desktop\main TA.xlsx", sheet_name="eg")

df1['start_date'] = df1['start_date'].dt.date
df1['end_date'] = df1['end_date'].dt.date

records1 = df1.where(pd.notnull(df1), None).to_records(index=False).tolist()

sql_delete = '''
    DELETE FROM eg;
'''

sql_insert = '''
    INSERT INTO eg (eg_id, ei, g_id, start_date, end_date) 
    VALUES (?, ?, ?, ?, ?)
'''

try:
    cursor = conn.cursor()
    cursor.execute(sql_delete)  
    
    for record in records1:
        cursor.execute(sql_insert, record)
    
    conn.commit()  
except Exception as e:
    conn.rollback()  
    print(f"Error: {str(e)}")
finally:
    cursor.close()
    conn.close()
    print('Task is complete.')

Task is complete.

In [12]:
# table 9


conn_str = (
    r'DRIVER={ODBC Driver 17 for SQL Server};'  
    r'SERVER=DESKTOP-D320OC2\SQLEXPRESS;'
    r'DATABASE=savina;'
    r'Trusted_Connection=yes;'
)

try:
    conn = pyodbc.connect(conn_str)
except pyodbc.Error as ex:
    print(f"Connection Error: {ex}")
    raise

sql_delete = '''
    DELETE FROM el;
'''

df1 = pd.read_excel(r"C:\Users\HP\Desktop\main TA.xlsx", sheet_name="el")

df1['start_date'] = df1['start_date'].dt.date
df1['end_date'] = df1['end_date'].dt.date

records1 = df1.where(pd.notnull(df1), None).to_records(index=False).tolist()

sql_insert = '''
    INSERT INTO el (elob_id, ei, lob_id, start_date, end_date) 
    VALUES (?, ?, ?, ?, ?)
'''

try:
    cursor = conn.cursor()
    cursor.execute(sql_delete)  
    for record in records1:
        cursor.execute(sql_insert, record)
    conn.commit()  
except Exception as e:
    conn.rollback()  
    print(f"Error: {str(e)}")
finally:
    cursor.close()
    conn.close()
    print('Task is complete.')

Task is complete.

In [13]:
#table 10

import pandas as pd
import pyodbc
from datetime import date

conn_str = (
    r'DRIVER={ODBC Driver 17 for SQL Server};' 
    r'SERVER=DESKTOP-D320OC2\SQLEXPRESS;'
    r'DATABASE=savina;'
    r'Trusted_Connection=yes;'
)

try:
    conn = pyodbc.connect(conn_str)
except pyodbc.Error as ex:
    print(f"Connection Error: {ex}")
    raise

df1 = pd.read_excel(r"C:\Users\HP\Desktop\main TA.xlsx", sheet_name="teamleader")

df1['start_date'] = df1['start_date'].dt.date
df1['end_date'] = df1['end_date'].dt.date

records1 = df1.where(pd.notnull(df1), None).to_records(index=False).tolist()

sql_delete = '''
    DELETE FROM teamleader;
'''

sql_insert = '''
    INSERT INTO teamleader (etl_id, ei, team_leader, start_date, end_date) 
    VALUES (?, ?, ?, ?, ?)
'''

try:
    cursor = conn.cursor()
    cursor.execute(sql_delete)  
    for record in records1:
        cursor.execute(sql_insert, record)
    conn.commit()  
except Exception as e:
    conn.rollback()  
    print(f"Error: {str(e)}")
finally:
    cursor.close()
    conn.close()
    print('Task is complete.')

Task is complete.

In [14]:
#table 11


conn_str = (
    r'DRIVER={ODBC Driver 17 for SQL Server};' 
    r'SERVER=DESKTOP-D320OC2\SQLEXPRESS;'
    r'DATABASE=savina;'
    r'Trusted_Connection=yes;'
)

try:
    conn = pyodbc.connect(conn_str)
except pyodbc.Error as ex:
    print(f"Connection Error: {ex}")
    raise

df1 = pd.read_excel(r"C:\Users\HP\Desktop\main TA.xlsx", sheet_name="QA")

df1['start_date'] = df1['start_date'].dt.date
df1['end_date'] = df1['end_date'].dt.date

records1 = df1.where(pd.notnull(df1), None).to_records(index=False).tolist()

sql_delete = '''
    DELETE FROM qa;
'''

sql_insert = '''
    INSERT INTO qa (eqa_id, ei, PIC, start_date, end_date) 
    VALUES (?, ?, ?, ?, ?)
'''

try:
    cursor = conn.cursor()
    cursor.execute(sql_delete)  
    for record in records1:
        cursor.execute(sql_insert, record)
    conn.commit()  
except Exception as e:
    conn.rollback()  
    print(f"Error: {str(e)}")
finally:
    cursor.close()
    conn.close()
    print('Task is complete.')

Task is complete.

In [15]:
#table 12


conn_str = (
    r'DRIVER={ODBC Driver 17 for SQL Server};' 
    r'SERVER=DESKTOP-D320OC2\SQLEXPRESS;'
    r'DATABASE=savina;'
    r'Trusted_Connection=yes;'
)

try:
    conn = pyodbc.connect(conn_str)
except pyodbc.Error as ex:
    print(f"Connection Error: {ex}")
    raise

df1 = pd.read_excel(r"C:\Users\HP\Desktop\main TA.xlsx", sheet_name="target")

df1['start_date'] = df1['start_date'].dt.date
df1['end_date'] = df1['end_date'].dt.date

records1 = df1.where(pd.notnull(df1), None).to_records(index=False).tolist()

sql_delete = '''
    DELETE FROM target;
'''

sql_insert = '''
    INSERT INTO target (target_id, ei, target, start_date, end_date) 
    VALUES (?, ?, ?, ?, ?)
'''

try:
    cursor = conn.cursor()
    cursor.execute(sql_delete) 
    for record in records1:
        cursor.execute(sql_insert, record)
    conn.commit()  
except Exception as e:
    conn.rollback() 
    print(f"Error: {str(e)}")
finally:
    cursor.close()
    conn.close()
    print('Task is complete.')

Task is complete.

In [16]:
#table 13


conn_str = (
    r'DRIVER={ODBC Driver 17 for SQL Server};' 
    r'SERVER=DESKTOP-D320OC2\SQLEXPRESS;'
    r'DATABASE=savina;'
    r'Trusted_Connection=yes;'
)

try:
    conn = pyodbc.connect(conn_str)
except pyodbc.Error as ex:
    print(f"Connection Error: {ex}")
    raise

df1 = pd.read_excel(r"C:\Users\HP\Desktop\main TA.xlsx", sheet_name="resign")

df1['start_date'] = df1['start_date'].dt.date
df1['end_date'] = df1['end_date'].apply(lambda x: x.date() if pd.notnull(x) else None)

records1 = df1.where(pd.notnull(df1), None).to_records(index=False).tolist()

sql_delete = '''
    DELETE FROM resign;
'''

sql_insert = '''
    INSERT INTO resign (r_id, ei, status, start_date, end_date) 
    VALUES (?, ?, ?, ?, ?)
'''

try:
    cursor = conn.cursor()
    cursor.execute(sql_delete)  
    for record in records1:
        cursor.execute(sql_insert, record)
    conn.commit()  
except Exception as e:
    conn.rollback()  
    print(f"Error: {str(e)}")
finally:
    cursor.close()
    conn.close()
    print('Task is complete.')

Task is complete.